Test

diff --git a/.github/actions/tsscript/action.yml b/.github/actions/tsscript/action.yml
--- a/.github/actions/tsscript/action.yml
+++ b/.github/actions/tsscript/action.yml
@@ -8,14 +8,16 @@ inputs:
 runs:
   using: "composite"
   steps:
+    - name: Fail if script contains single quotes
+      if: contains(inputs.script, "'")
+      shell: bash
+      run: |
+        echo "::error::Single quotes are not supported yet (')."
+        exit 1
     - name: Execute ts
       shell: bash
       run: |
         # Executing TS script
-        if [[ "${{ inputs.script }}" == *"'"* ]]; then
-          echo "::error::Single quotes are not supported yet (')."
-          exit 1
-        fi
         bun run - <<'EOF'
           ${{ inputs.script }}
         EOF
