Updated workflow

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -34,7 +34,7 @@ jobs:
         run: rome check --apply . || true
 
       - name: Save rome errors
-        run: echo "ERROR=$(rome check --json . || true)" >> $GITHUB_ENV
+        run: echo 'ERROR=$(rome check --json . || true)' >> $GITHUB_ENV
 
       - name: Clean Rome config file
         run: rm rome.json
