Updated workflow

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -35,10 +35,7 @@ jobs:
 
       - name: Save rome errors
         id: rome_errors
-        run: |
-          RESULT=$(rome check --json .)
-          echo "ERROR=$RESULT" >> $GITHUB_ENV
-        continue-on-error: true
+        run: echo "ERROR=$(rome check --json . || true)" >> $GITHUB_ENV
 
       - name: Clean Rome config file
         run: rm rome.json
